# -*- coding: utf-8 -*-
"""TAWNT public API.

The implementation is separated by responsibility under ``startech.tawnt``. This
facade keeps the existing ``import tawnt`` contract stable. TAWNT validates
software declarations and motor commands; it neither writes GPIO/PWM nor proves
that a physical motor stopped.
"""

from startech.tawnt.faults import (
    configureFaultStore,
    declareUnexpectedSigint,
    flushPWM,
    kilitDurumu,
    latchFault,
    onShutdown,
    resetFault,
)
from startech.tawnt.model import (
    ARMED,
    BENCH,
    BOOT,
    DEFINED,
    DEVRALINDI,
    LATCHED_FAULT,
    LIVE,
    MUTED,
    OLCULDU,
    OFFLINE,
    READY_UNARMED,
    RECORDED,
    SEALED,
    STALE,
    STOP,
    VALIDATED,
    VALIDATING,
    VARSAYILDI,
    WARNING,
    TawntHatasi,
    ValidatedMotorCommand,
)
from startech.tawnt.motion import (
    arm,
    checkWatchdogs,
    definePhase,
    defineWatchdog,
    disarm,
    enterPhase,
    evreDegisti,
    heartbeat,
    isMotionAllowed,
    pwmSerbestMi,
    systemState,
    validateMotorCommand,
    validatePhase,
)
from startech.tawnt.runtime import sifirla
from startech.tawnt.scanner import scanDirectMotorWrites
from startech.tawnt.values import (
    IsTwinOf,
    acquire,
    defineValue,
    deger,
    dependsOn,
    differenceSkew,
    identifyRuntimeType,
    introduce,
    preacquire,
    recordValue,
    report,
    requireMeasured,
    seal,
    siblingIntAppr,
    validateBeforeStart,
    valueState,
)


__all__ = [
    "TawntHatasi",
    "ValidatedMotorCommand",
    "OLCULDU",
    "VARSAYILDI",
    "DEVRALINDI",
    "OFFLINE",
    "BENCH",
    "LIVE",
    "DEFINED",
    "RECORDED",
    "VALIDATED",
    "STALE",
    "SEALED",
    "BOOT",
    "VALIDATING",
    "READY_UNARMED",
    "ARMED",
    "MUTED",
    "LATCHED_FAULT",
    "WARNING",
    "STOP",
    "defineValue",
    "recordValue",
    "dependsOn",
    "requireMeasured",
    "validateBeforeStart",
    "seal",
    "valueState",
    "systemState",
    "definePhase",
    "enterPhase",
    "validatePhase",
    "arm",
    "disarm",
    "isMotionAllowed",
    "validateMotorCommand",
    "defineWatchdog",
    "heartbeat",
    "checkWatchdogs",
    "configureFaultStore",
    "latchFault",
    "resetFault",
    "scanDirectMotorWrites",
    "introduce",
    "acquire",
    "preacquire",
    "identifyRuntimeType",
    "IsTwinOf",
    "siblingIntAppr",
    "differenceSkew",
    "deger",
    "report",
    "sifirla",
    "declareUnexpectedSigint",
    "flushPWM",
    "evreDegisti",
    "pwmSerbestMi",
    "onShutdown",
    "kilitDurumu",
]
